[package]
name = "StormParser"
version = "0.1.0"
authors = ["Toby Lawrence <toby@nuclearfurnace.com>"]

[lib]
name = "storm_parser"
path = "src/lib.rs"

[[bin]]
name = "storm-parser"
path = "src/bin.rs"

[dependencies]
mpq = { path = "../mpq-rust" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
byteorder = "1.1.0"
